### ISSUE TITLE
Allow for multiple terms and definitions

### ISSUE THREAD

**Issue by hacknug** [lassemt/wp-block-description-list#2]
Description lists can have multiple terms and definitions.

Right now your block only allows for pairs of _just one_ term and _just one_ definition. Adding multiple lines on text inside each of those fields adds `<br />` inside of them. Trying to workaround this by adding multiple pairs and leaving one of the fields empty causes the content on those rows to not being rendered.

I'd expect the plugin to produce one `<dt>` and one `<dd>` per line in each of its fields. This would be far better than rendering the fields individually regardless the other one is empty or not (which could work as a temporary solution imho).

Having those line-breaks could be definitely useful in some cases so maybe the solutions would be to allow nesting paragraph blocks inside both the term and the definition fields?

EDIT: great plugin, btw. As a `<dl>` fan, I consider this to be the most helpful block released so far ✨

**Comment by lassemt** [comment]
This was a bit unclear for me, but looking further into the spec of description lists I think I have a understanding:

A description list should be able to have a single term and multiple descriptions:
```
<dl>
  <dt>Firefox</dt>
  <dd>
    A free, open source, cross-platform,
    graphical web browser developed by the
    Mozilla Corporation and hundreds of
    volunteers.
  </dd>
  <dd>
    The Red Panda also known as the Lesser
    Panda, Wah, Bear Cat or Firefox, is a
    mostly herbivorous mammal, slightly larger
    than a domestic cat (60 cm long).
  </dd>

  <!-- Other terms and descriptions -->
</dl>
```
or a single term with multiple descriptions:
```
<dl>
  <dt>Firefox</dt>
  <dd>
    A free, open source, cross-platform,
    graphical web browser developed by the
    Mozilla Corporation and hundreds of
    volunteers.
  </dd>
  <dd>
    The Red Panda also known as the Lesser
    Panda, Wah, Bear Cat or Firefox, is a
    mostly herbivorous mammal, slightly larger
    than a domestic cat (60 cm long).
  </dd>

  <!-- Other terms and descriptions -->
</dl>
```
and so on. The examples from the [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl) are quite good at explaining it.

It should be a easy fix, so I'll take a look on it ASAP. 

Thanks for pointing this out and your kind words✌🏼

**Comment by lassemt** [comment]
@hacknug If you try out the build in [this branch.](https://github.com/lassemt/wp-block-description-list/tree/fix-newlines) and let me know what you think. It should be correctly according to the spec. 

Now you have the option to insert terms `<dt>` and `<dd`> separately. I used a simple hack to disable line breaks in `<dt>`. The hack can be used to insert a `dd` or `dt` on enter, but this is something I will have to do some user testing on to decide what should be inserted. I will be creating a enhancement issue for this.

According to the spec [flow content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Flow_content) is permitted as content for `<dd>`, that is why I choose to use inner blocks for that one. Currently I have enabled paragraph and image, do you have any thoughts on this?

The UI is not as simple as the pervious one, but it is working. I will look further into this on what I can do to improve the experience. 

Let me know what you think, and thanks again for pointing this out to me 😊 Under is attached some images how it looks now and the outputted code:

<img width="778" alt="screen shot 2018-12-14 at 15 44 04" src="https://user-images.githubusercontent.com/2833312/50010228-1c157100-ffb9-11e8-971c-ab092683000c.png">
![screen shot 2018-12-14 at 15 57 56](https://user-images.githubusercontent.com/2833312/50010238-2172bb80-ffb9-11e8-9703-7ed2e5387e0c.png)

**Output markup:**
 ´´´

**Comment by hacknug** [comment]
Looks good to me!

Not sure about how important is this but: if you leave an empty paragraph block inside a description this will render (obviously) an empty paragraph tag. This could cause spacing issues if the list's `display` property is set to `flex` or `grid`.

Since you weren't rendering empty fields before, maybe the plugin should do the same now unless this is the behavior of the core paragraph block.

Regarding inner blocks, ideally we should allow for other blocks like embeds, video, audio, lists, quotes and blockquotes, preformated text, buttons and headings (just to name a few of the blocks I have in mind now). Even nested definitions lists should be allowed according to the spec if I'm not mistaken. Also flow content is permitted inside `<dt>` not just inside `<dd>`.

The issue here imho is that things could get messy real fast and I don't think Gutenberg's UI is mature enough to handle those use cases.

In this case I'd simply leave it like you have it now and add specific blocks when requested via a new issue in the repo (before this gets merged into core or we get an alternative there).

Thanks for solving it so fast!

**Comment by lassemt** [comment]
Thanks for the fast feedback!

The empty paragraph is unfortunately the behavior of the core paragraph block.. I can probably filter this on save.

About the content in `<dt>` and `<dd>` they have the same spec except `<dt>` is permitted flow content with no <header>, <footer>, sectioning content or heading content descendants. So the ultimate solution is that `<dt>` and `<dd>` is the same "block" where you can switch between the tags. And if `<dt>` is selected, heading content are converted into paragraphs. I see know this is what I should have done from the start. What do you think?

I agree the UI gets messy quite fast now. There is not much I can do about the heights of the blocks, but I can try to indent the `<dd>` more. I also need to find a way that "shows" and make the `<dt>` and `<dd>`more clickable.

**Comment by hacknug** [comment]
I'd leave the empty paragraph there then. Better not to do any extra work if it's the default behavior. Maybe we can open an issue in Gutenberg's repo to discuss it with the team.

Headings should not be converted to paragraphs since they're just headings and not a sectioning `<header>` element. They're allowed if I'm not mistaken.

This plugin's UI is pretty okay imho. We'll see what happens in core once/when we can add blocks inside list items and maybe we can revisit later unless real issues arise when using it.

**Comment by lassemt** [comment]
The block should follow the spec quite well now. If you take a look [in this branch](https://github.com/lassemt/wp-block-description-list/tree/follow-spec). 

The spec for `<dt>`says: 
> Flow content, but with no `<header>`, `<footer>`, sectioning content or heading content descendants.

and elements belonging to the heading content being `<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`, `<h6>` and `<hgroup>` ([source](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Heading_content)). So I decided to transform headings to paragraphs when going from `<dd>` to `<dt>`. Have a look at this funky button: 
![screen shot 2018-12-14 at 22 49 04](https://user-images.githubusercontent.com/2833312/50029277-8a2a5a00-fff2-11e8-8798-35c7f38c96dc.png)

Only problem now is the that its a bit hard to see what is `<dd>` and what is `<dt>`. This is discussed in another issue ( #3 )

I can't find anything else to do with it now to make it fit the spec more, so I'll merge this into master if you think it looks alright :)

**Comment by hacknug** [comment]
You’re right. I guess I never read that bit haha
